#
# Module manifest for module 'BlockchainAPI'
#
# Generated by: sn0rlacks
#
# Generated on: 1/24/2022
#

@{
RootModule = 'BlockchainAPI.psm1'
ModuleVersion = '2.0'
GUID = 'd81cac28-a3f8-48ef-bca6-8ebf19ea6577'
Author = 'Joshua C. aka sn0rlacks'
CompanyName = 'Unknown'
Copyright = '(c) sn0rlacks. All rights reserved.'
Description = 'Powershell wrapper for the BlockchainAPI by Josh Wolff!'
PowerShellVersion = '7.0'
FunctionsToExport = @('Add-NFTListing', 'Get-TokensInWallet', 'Enter-BlockchainAPI', 'Remove-NFTListing', 'Get-NFTInWallet', 'Get-SolanaWalletBalance', 'Send-SPLToken', 'New-SecretPhrase', 'New-PrivateKey', 'Find-PrivateKey', 'Find-PublicKey')
CmdletsToExport = @()
VariablesToExport = '*'
AliasesToExport = @()
}

